#!/usr/bin/env zsh
# get the dir where this script is stored
script_dir="$(dirname $0:A)"
#for vim session management:
export PATHTOSESSION="$script_dir"

#i3-msg "workspace 3; append_layout $script_dir/workspaces/three.json"
#sleep 1 &&
#start vim with session management
urxvtc -e vim -u "$script_dir"/../../vimrc
# start vim with all-packages.nix
urxvtc -e vim ~/source/nixpkgs/pkgs/top-level/all-packages.nix
#start vim in pkgs dir
#urxvtc -e vim ~/source/nixpkgs/pkgs/
#sleep 1 &&
#i3-msg "workspace 4; append_layout $script_dir/workspaces/four.json"
#sleep 1 &&
#cd ~/nixosConfig/ & urxvtc
#cd ~/.dot & urxvtc
#cd ~/source/nixpkgs/ & urxvtc
