#!/bin/sh
#/nix/store/ma91zxra9s1kq2mx3li8wji9akf959in-zsh-5.0.5/bin/zsh

./open https://www.google.com/ncr#q=\"$(sselp)\"&tbs=li:1
#./open http://duckduckgo.com/?q=$(sselp)
#firefox https://www.google.com/ncr#q=\"$(sselp)\"&tbs=li:1

