#!/usr/bin/env zsh

#NAME=$0:t

#fpath+=$WMII_PATH/functions
#autoload zargs
#autoload dmenu
#autoload pick-web-browser

#ARGS=(${@:-$(sselp)})
ARGS=(${@})

# input can be edited
#URI=$(print -l $ARGS | dmenu -p $NAME -l 10)

if [ -n "$ARGS" ]; then
    firefox "$ARGS"
fi

#[[ -n "$URI" ]] || exit
#URI=${URI#file:/}
#if [[ -f "$URI" ]]; then
#	run-mailcap --action=view "$URI"
#else
#	pick-web-browser "$URI"
#	xdg-open "$URI"
#fi
