#!/usr/bin/env zsh
# get the dir where this script is stored
script_dir="$(dirname $0:A)"
#for vim session management:
export PATHTOSESSION="$script_dir"

# Clean out the workspace, ready for the new windows
i3-msg 'rename workspace 1 to "junk1"'
# Load Python documentation, 2 browser windows into a tabbed container
i3-msg "workspace 1; append_layout "$script_dir"/workspaces/testi3"

cd ~/
#start vim with session management
urxvtc -e vim -u "$script_dir"/../../vimrc
urxvtc
