[mgr]

prepend_keymap = [
# swap z and Z:
	{ on = "Z",         run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },
	{ on = "z",         run = "plugin zoxide",               desc = "Jump to a directory via zoxide" },

# q closes a tab, not the whole app:
	{ on = "q", run = "close",              desc = "Close the current tab, or quit if it's last" },

    { on = "l",         run  = "plugin fast-enter",          desc = "Enter the subfolder faster, or open the file directly" },

    { on = "M",         run = "plugin mount",                desc = "Mount a disk" },

    { on = "F",         run = "plugin smart-filter",         desc = "Smart filter" },

    { on = [ "P", "s" ], run = "plugin projects save", desc = "Save current project"},
    { on = [ "P", "l" ], run = "plugin projects load", desc = "Load project"},
    { on = [ "P", "P" ], run = "plugin projects load_last", desc = "Load last project"},
    { on = [ "P", "d" ], run = "plugin projects delete", desc = "Delete project"},
    { on = [ "P", "D" ], run = "plugin projects delete_all", desc = "Delete all projects"},
    { on = [ "P", "m" ], run = "plugin projects 'merge current'", desc = "Merge current tab to other projects"},
    { on = [ "P", "M" ], run = "plugin projects 'merge all'", desc = "Merge current project to other projects"},

    { on   = "!",        run  = 'shell "$SHELL" --block',     desc = "Open $SHELL here"},

    ]
