#!/run/current-system/sw/bin/zsh

# get the dir where this script is stored
script_dir="$(dirname $0:A)"
#for vim session management:
export PATHTOSESSION="$script_dir"


cd "$dirname"/../../
#start vim with session management
urxvtc -e vim -u "$script_dir"/../../vimrc

#todo:
#
#  https://github.com/michaelmrose/vi3
#
#function saveme
    #i3-save-tree --workspace (getCurrentWorkspace)  | sed 's-^\([[:blank:]]*\)//\([[:blank:]]"class".*\),$-\1\2-' >  ~/.i3/sessions/{$argv}.json
    #set sessionscript ~/sessions/{$argv}
    #echo '#!/usr/bin/fish' >  $sessionscript
    #chmod +x $sessionscript
    #eval $EDITOR $sessionscript
#end

#(10:58:02 PM) michaelrose: I have a function saveme that does save tree pipes it through sed to uncomment just the window class saves it to ~/.i3/sessions/foo where foo is the arg to the function, it then creates a shell script named foo, in another dir from a template, makes it executable, and opens it in my editor, I write the programs that should start, write quit bam done
#(10:58:33 PM) michaelrose: basically I do saveme foo, enter the apps that should start and how, :wq<RETURN> and am done
