#!/usr/bin/env zsh


# customize dmenu as you see fit
DMENU_COMMAND="dmenu -b -i  -nb \#3F3F3F -nf \#FAFAD2 -sb \#ffff00 -sf \#000000 -p edit:"

# get the dir where this script is stored
script_dir="$(dirname $0:A)"

# go to the scripts dir
cd "$script_dir"/scripts/

# get subdirs of current dir | pipe into dmenu
cur_ses=$(ls -d */ | sed -e "s/\///g" | eval $DMENU_COMMAND)

if [ -z "$cur_ses" ]; then
  exit
else
  if [ ! -d  $PWD/"$cur_ses"/ ]; then
    mkdir -p $PWD/"$cur_ses"/
    cp ~/.config/i3/scripts/dzshmenu/sessiontemplate  $PWD/"$cur_ses"/zshsession
    chmod +x $PWD/"$cur_ses"/zshsession
  fi

  # edit the session script
  urxvtc -e vim $PWD/"$cur_ses"/zshsession
fi

