#!/usr/bin/env zsh

# customize dmenu as you see fit
DMENU_COMMAND="dmenu -i  -nb \#3F3F3F -nf \#FAFAD2 -sb \#ffff00 -sf \#000000 -p launch:"

# get the dir where this script is stored
script_dir="$(dirname $0:A)"

 # go to the scripts dir
cd "$script_dir"/scripts/
# get subdirs of current dir | pipe into dmenu
cur_ses=$(ls -d */ | sed -e "s/\///g" | eval $DMENU_COMMAND)

if [ -z "$cur_ses" ]; then
  exit
else
  # write the result in a file, to be used later
  echo "$cur_ses" > $script_dir/current_session
  # run the script
  exec "$cur_ses"/zshsession
fi
