#!/usr/bin/env zsh

# customize dmenu as you see fit
DMENU_COMMAND="dmenu -b -i  -nb \#3F3F3F -nf \#FAFAD2 -sb \#ffff00 -sf \#000000 -p 'new session name:'"

# get the dir where this script is stored
script_dir="$(dirname $0:A)"

if [ -z "$1" ]; then
   # go to the scripts dir
  cd "$script_dir"/scripts/
  # get subdirs of current dir | pipe into dmenu
  input="$( printf "" | eval $DMENU_COMMAND )"
else
  input="$1"
fi

if [ "$input" != '' ]; then
  echo $input > "$script_dir"/current_session
  new_dir="$script_dir/scripts/$input"
  if [ -d "$new_dir" ]; then
    echo "session directory already exists: editing."
  else
    mkdir "$new_dir"
    touch "$new_dir"/zsh_history
    cp "$script_dir"/sessiontemplate "$new_dir"/zshsession
  fi
  #urxvtc doesn't work in this case, as it exits instantly
  urxvt -e vim "$new_dir"/zshsession
  exec "$new_dir"/zshsession
fi
