#!/run/current-system/sw/bin/zsh

# customize dmenu as you see fit
DMENU_COMMAND="dmenu -b -i  -nb \#3F3F3F -nf \#FAFAD2 -sb \#ffff00 -sf \#000000 -p edit:"

# go to the scripts dir
cd ~/.config/i3/scripts/dzshmenu/scripts/

if [ "$1" != '' ]; then
  echo $1 > $PWD/current_session
  new_dir="$PWD/$1"
  if [ -d $new_dir ]; then
    echo "session directory already exists: editing."
  else
    mkdir $new_dir
    touch $new_dir/zsh_history
    cp ~/.config/i3/scripts/dzshmenu/sessiontemplate $new_dir/zshsession
    chmod +x $new_dir/zshsession
  fi
  vim $new_dir/zshsession
  exec $new_dir/zshsession
fi
