#!/run/current-system/sw/bin/zsh

# get the dir where this script is stored
script_dir="$(dirname $0:A)"
#for vim session management:
export PATHTOSESSION="$script_dir"
# sessionized history
#export HISTFILE="$script_dir/zsh_history"
#fc -p -a $PATHTOSESSION/zsh_history
#echo $HISTFILE



cd ~/
#start vim with session management
urxvtc -e vim -u "$script_dir"/../../vimrc

