#!/run/current-system/sw/bin/zsh

# get the dir where this script is stored
script_dir="$(dirname $0)"
# go to the scripts dir
#cd "$script_dir"/scripts/
# get the current session dir
#read -r cur_ses < "$script_dir"/current_session 
#for vim session management:
export PATHTOSESSION="$script_dir"
#export HISTFILE="$PATHTOSESSION/zsh_history"
#fc -p -a $PATHTOSESSION/zsh_history
#echo $HISTFILE

#start vim with session management
urxvtc -e vim -u ~/.config/i3/scripts/dzshmenu/vimrc

