#!/run/current-system/sw/bin/zsh

# go to the scripts dir
cd ~/.config/i3/scripts/dzshmenu/scripts/
# go to the current session dir
cd $(cat $PWD/current_session)
#for vim session management:
export PATHTOSESSION=$PWD
#export HISTFILE="$PATHTOSESSION/zsh_history"
#fc -p -a $PATHTOSESSION/zsh_history
#echo $HISTFILE

#start vim with session management
urxvtc -e vim -u ~/.config/i3/scripts/dzshmenu/vimrc

