icons         = "awesome"

[theme]
name          = "slick"

[theme.overrides]
idle_bg       = "#DCDAD5"
idle_fg       = "#3F3F3F"
info_bg       = "#DCDAD5"
info_fg       = "#3F3F3F"
good_bg       = "#DCDAD5"
good_fg       = "#3F3F3F"
warning_bg    = "#DCDAD5"
warning_fg    = "#0000FF"
critical_bg   = "#DCDAD5"
critical_fg   = "#00FFFF"

# [[block]]
# block       = "networkmanager"

[[block]]
block         = "net"
device        = "enp0s25"
ssid          = false
ip            = true
speed_up      = false
speed_down    = false
graph_up      = false
graph_down    = false
interval      = 1
hide_inactive = true
hide_missing  = true

[[block]]
block         = "net"
device        = "wlp3s0"
ssid          = true
ip            = true
speed_up      = false
speed_down    = false
graph_up      = false
graph_down    = false
interval      = 1
hide_inactive = true
hide_missing  = true

[[block]]
block         = "disk_space"
path          = "/"
alias         = ""
info_type     = "available"
interval      = 20
warning       = 20.0
alert         = 10.0

[[block]]
block         = "disk_space"
path          = "/home/"
alias         = ""
info_type     = "available"
interval      = 20
warning       = 20.0
alert         = 10.0

[[block]]
block         = "memory"
display_type  = "memory"
format_mem    = "{MFg}GB"
format_swap   = "{SFg}GB"

[[block]]
block         = "cpu"
interval      = 1

[[block]]
block         = "temperature"
collapsed     = true
interval      = 10
format        = "{min}° min, {max}° max, {average}° avg"

[[block]]
block         = "backlight"

[[block]]
block         = "sound"

[[block]]
block         = "battery"
format        = "{percentage}% {time}"

[[block]]
block         = "time"
interval      = 60
format        = "%a %d/%m %R"
