# theme                   = "solarized-light"
# theme = "gruvbox-light"
# theme = "bad-wolf"
# theme = "modern"
# theme = "slick"
icons                   = "awesome"
[theme]
name = "slick"
[theme.overrides]
idle_bg = "#DCDAD5"
idle_fg = "#3F3F3F"
info_bg = "#DCDAD5"
info_fg = "#3F3F3F"
good_bg = "#DCDAD5"
good_fg = "#3F3F3F"
warning_bg = "#DCDAD5"
warning_fg = "#0000FF"
critical_bg = "#DCDAD5"
critical_fg = "#00FFFF"
# separator = "|"
# separator_bg = "#FFFFFF"
# separator_fg = "#FFFFFF"
# alternating_tint_bg = "#DCDAD5"
# alternating_tint_fg = "#3F3F3F"
# [[block]]
# name                    = "networkmanager"


[[block]]
block                   = "net"
device                  = "enp0s25"
ssid                    = false
ip                      = true
speed_up                = true
speed_down              = true
graph_up                = false
graph_down              = false
interval                = 5

[[block]]
block                   = "net"
device                  = "wlp3s0"
ssid                    = true
ip                      = true
speed_up                = true
speed_down              = true
graph_up                = false
graph_down              = false
interval                = 5

[[block]]
block                   = "disk_space"
path                    = "/"
alias                   = ""
info_type               = "available"
interval                = 20
warning                 = 20.0
alert                   = 10.0

[[block]]
block                   = "disk_space"
path                    = "/home/"
alias                   = ""
info_type               = "available"
interval                = 20
warning                 = 20.0
alert                   = 10.0

[[block]]
block                   = "maildir"
interval                = 60
inboxes                 = ["/home/bart/.mail/INBOX"]
threshold_warning       = 1
threshold_critical      = 10

# [[block]]
# block = "focused_window"
# max_width = 21


[[block]]
block                   = "memory"
display_type            = "memory"
format_mem              = "{Mup}%"
format_swap             = "{SUp}%"

[[block]]
block                   = "cpu"
interval                = 1

[[block]]
block                   = "temperature"
collapsed               = false
interval                = 10
format                  = "{min}° min, {max}° max, {average}° avg"

[[block]]
block                   = "backlight"

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block                   = "sound"

[[block]]
block                   = "battery"
format                  = "{percentage}% {time}"

[[block]]
block                   = "time"
interval                = 60
format                  = "%a %d/%m %R"
