#!/run/current-system/sw/bin/zsh

# get the dir where this script is stored
script_dir="$(dirname $0:A)"
#for vim session management:
export PATHTOSESSION="$script_dir"


cd ~/.config/i3/
#start vim with session management
urxvtc -e $EDITOR --cmd "source "$script_dir"/../../vimrc"

