#!/run/current-system/sw/bin/zsh


cd ~/.dzshmenu/
cd $(cat $PWD/current_session)
export PATHTOSESSION=$PWD                         #for vim session management
#export HISTFILE="$PATHTOSESSION/zsh_history"
#fc -p -a $PATHTOSESSION/zsh_history

#echo $HISTFILE

#start vim with session management

cd ~/.config/i3/
urxvtc -e vim -u ~/.dzshmenu/vimrc ~/.config/i3/
