# "window.opacity" = 1

[bell]
animation = "EaseOutQuint"
color = "0x268bd2"
duration = 80

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#268bd2"
text = "0xfdf6e3"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
foreground = "0x444444"

[cursor]
# shape = "Block"

[font]
size = 7.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "Terminus"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
# mode = "~Search"
mods = "Control"

[terminal]

# [terminal.shell]
# program = "/run/current-system/sw/bin/fish"
