#!/usr/bin/env zsh
# get the dir where this script is stored
script_dir="$(dirname $0:A)"
#for vim session management:
export PATHTOSESSION="$script_dir"


#start vim with session management
urxvtc -e $EDITOR --cmd "source "$script_dir"/../../vimrc"
#urxvtc
